### ISSUE TITLE
Chyrons older than 24 days?

### ISSUE THREAD

**Issue by elliottmorris** [hrbrmstr/newsflash#10]
Hi there, 

I'm using your package to get long-term chyron data on hurricanes, similar to your example on [R-Bloggers](https://www.r-bloggers.com/retrieve-process-tv-news-chyrons-with-newsflash/amp/). My problem is that I can't get any chyron data prior to September 7, which complicates an analysis of hurricanes in July and August.

Is there a way to make those earlier chyrons available with the `list_chyrons()` function?

Thanks in advance. 

Elliott

**Comment by hrbrmstr** [comment]
From <https://archive.org/services/third-eye.php> (and the 6th bullet in the Description part of the `read_chyrons()` R 📦 manual):

> • We began collecting raw data on August 25, 2017; the filtered feed begins on September 7, 2017.
