### ISSUE TITLE
Error in loadNamespace - there is no package called `txtplot`

### ISSUE THREAD

**Issue by jrosen48** [hrbrmstr/newsflash#2]
When I installed via `devtools::install_github()`, the following error was returned:

```
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘txtplot’
```

I simply installed `txtplot` using `install.packages('txtplot')`, but wondered if this had to do with it not being included in the namespace.

**Comment by hrbrmstr** [comment]
aye. lemme fix the imports/DESCRIPTION real quick. #ty for the issue!
